#:schema ../../Resource%20Schema/Course.json

title = "[title]"
description = """Published by [publisher], license [license]
Downloaded from [url] on [date]

This course was created for use in the Kat's Bookshelf collection."""

# Converted into EPUB using textbook-dl

# [[books]]
# label = "Volume 1"
# file  = ""
#
# [[books.chapters]]
# root = ""
#
# [[books.chapters.groups]]
# sections = [""]
